FROM debian:13

WORKDIR /builds/afonsodemori/packages

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    ca-certificates \
    sudo \
    gnupg \
    dpkg-dev \
    apt-utils \
    curl \
    wget \
    vim \
    && apt-get autoremove -y && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/*
